version: '3.8'

services:
  app:
    image: ghcr.io/kezzyy/ppu:latest
    container_name: shimatsu-updater
    restart: always
    ports:
      - "3008:3008"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/backend/uploads
      - ./storage:/app/backend/storage

  db:
    image: postgres:15-alpine
    container_name: shimatsu-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shimatsu_updater
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: shimatsu-redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
